data:
  load_path: "..\\data\\judge_prompt_reference.csv"
  save_path: "..\\results\\claude_judge_answer_reference.csv"
  text_column: # list of columns to include in the user_prompt
    - 'judge_prompt' 
  answer_column: # list of columns to store answers
    - 'judge_answer' 
  
model:
  model_name: "claude-3-5-sonnet-20241022"
  temperature: 0.8
  max_tokens: 1024
  chunk_size : 50
  sleep_time : 1
  max_iterations : 7

prompt:
  system: "You are an expert in policing and law enforcement."
  
  tools:
    - name: "answer_json"         
      description: "사용자 질문에 대한 응답을 json으로 생성합니다"  
      input_schema:
        type: "object"              
        properties:
          feedback:
            type: "string"
            description: "concise feedback on the AI assistant's response in Korean"
          score:
            type: "number"
            description: "evaluation score as a number from 1(lowest) to 5(highest)"
        required: ["feedback", "score"]

  